<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="integrationmm" nsURI="http://www.example.org/integrationmm"
    nsPrefix="integrationmm">
  <eClassifiers xsi:type="ecore:EClass" name="LinkModel" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftModels" lowerBound="1"
        upperBound="-1" eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightModels" lowerBound="1"
        upperBound="-1" eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftMEs" lowerBound="1"
        upperBound="-1" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightMEs" lowerBound="1"
        upperBound="-1" eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement"/>
</ecore:EPackage>
